### ISSUE TITLE
BAD timestamp from Weather Meter.ini

### ISSUE THREAD

**Issue by Gradius2** [SilverAzide/Gadgets#98]
I started to getting this error today (out of nothing), it worked perfectly from many months.  .ini seems fine:

```
[MeasureCurrentObservationDate]
Measure=Time
Group=Times
Disabled=1
TimeStamp=[@CurrentObservationTimeStamp]
TimeStampFormat=%Y-%m-%dT%H:%M:%S
Format=#DateFormat#
DynamicVariables=1

[MeasureCurrentObservationTime]
Measure=Time
Group=Times
Disabled=1
TimeStamp=[@CurrentObservationTimeStamp]
TimeStampFormat=%Y-%m-%dT%H:%M:%S
Format=#TimeFormat#
DynamicVariables=1
```

**Error:**
Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S (Gadgets\Weather Meter\Weather Meter.ini - [MeasureCurrentObservationTime])

**Comment by Gradius2** [comment]
Fixed.  APIkey changed!

**Comment by JamesTX10** [comment]
I updated that file, saved it, closed rainmeter and started it again and still have the same error in the log

**Comment by Second-DK** [comment]
> I updated that file, saved it, closed rainmeter and started it again and still have the same error in the log

Well, i updated the file and it worked for me..

**Comment by JamesTX10** [comment]
C:\Users\JamesTX10\Documents\Rainmeter\Skins\Gadgets\@Resources\WeatherComJSONVariables.inc

Changed line 37 from:
`APIKey=21d8a80b3d6b444998a80b3d6b1449d3`
To
`APIKey=71f92ea9dd2f4790b92ea9dd2f779061`

**Comment by jrtward** [comment]
Thank you,

This worked for me as well.

**Comment by SilverAzide** [comment]
Thanks everyone!  Patch will be coming out shortly!
